"""empty message

Revision ID: 49831f85dda5
Revises: ffdc0a98111c
Create Date: 2021-11-16 10:53:32.109381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49831f85dda5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
