"""empty message

Revision ID: 0481e2e8abbc
Revises: e6999daf4674
Create Date: 2021-11-21 17:26:30.784595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0481e2e8abbc'
down_revision = 'e6999daf4674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_boards', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_boards', 'title')
    # ### end Alembic commands ###
