"""empty message

Revision ID: b612e4b116a9
Revises: ed37bdf0da96
Create Date: 2021-11-16 11:41:27.822215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b612e4b116a9'
down_revision = 'ed37bdf0da96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('photoUrl', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_photos')
    # ### end Alembic commands ###
