"""empty message

Revision ID: e6999daf4674
Revises: a07ccb02144f
Create Date: 2021-11-17 13:09:08.372978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6999daf4674'
down_revision = 'a07ccb02144f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('discount', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('condition', sa.String(length=15), nullable=False))
    op.add_column('items', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'count')
    op.drop_column('items', 'condition')
    op.drop_column('items', 'discount')
    # ### end Alembic commands ###
