"""empty message

Revision ID: a07ccb02144f
Revises: b612e4b116a9
Create Date: 2021-11-16 13:02:55.189616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ccb02144f'
down_revision = 'b612e4b116a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'icon',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'icon',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
